# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: frontend/
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.41.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.42.0
          - eslint-config-prettier@8.8.0
          - eslint-plugin-prettier@4.2.1
        files: frontend/\.[jt]sx?$
        types: [file]
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
      - id: go-fmt-import
        files: backend/\.go$
      - id: go-unit-tests
        files: backend/\.go$
